### ISSUE TITLE
RTL Languages Support

### ISSUE THREAD

**Issue by DholaSain** [iakmds/markdown_toolbar#1]
Please add the RTL (right to left) language support. There are already many packages but no one has complete support for them.

**Comment by DholaSain** [comment]
> 

Yes, all the styling formats including bullets and alignments.

This is an example editor.
https://froala.com/wysiwyg-editor/examples/editor-direction/

**Comment by iakmds** [comment]
Hi @DholaSain,

After trying out some things regarding RTL support I noticed that by setting `textDirection: TextDirection.rtl` in your custom TextField RTL support is there out of the box - including the buttons like ordered lists, checkboxes, etc.

I published a new version with more customization options. Let me know if I can close this issue :smile:

**Comment by DholaSain** [comment]
I've tested it. You have done a great job. Awesome.
Thank you.
